### ISSUE TITLE
spinner.fail is not a function! error when trying to install missing package(new rule created)

### ISSUE THREAD

**Issue by kshyju** [sonarwhal/sonarwhal#1044] opened 2018-05-09 20:29 UTC
I ran `yarn new:rule` from the root directory to create a new rule and it gave me the interactive wizard to specify the meta information about the rule. After creating the rule, I ran  the command the wizard gave me to init the rule. As per the documentation, i should be able to start using the rule. So i updated the config json to include this rule and when i ran `sonarwhal` command, it gave me a message saying 1 package is missing and i want to install it . I opted "Yes" and i got an error message **spinner.fail  is not a function!**

![image](https://user-images.githubusercontent.com/144469/39837904-9800e580-538c-11e8-9f95-4ab90e2b6539.png)

## Environment

* __`sonarwhal` version:__  1.6.1
* __`Node.js` version:__ 8.11.1
* __`npm` version:__ 5.8.0

## `sonarwhal` configuration

<details>
<summary>sonarwhal’s configuration</summary>

```
{
    "connector": {
        "name": "chrome",
        "options": {
            "waitFor": 1000
        }
    },
    "formatters": ["summary", "excel"],
    "parsers": [],
    "rulesTimeout": 120000,
    "rules": {
        "content-type": "warning",
        "my-new-rule-name": "warning",      
        "http-cache": "warning"

    }
}
```

## URL for which `sonarwhal` failed

* __URL:__

## Output

Please include the raw output generated by `sonarwhal`, or if possible,
the raw output from running `sonarwhal` in debug mode: `sonarwhal --debug <URL>`.

<details>
<summary>sonarwhal’s raw output</summary>

```text



```

</details>

**Comment by molant** [comment] 2018-05-09 20:47
A couple of things we need to do:

* Update the docs to execute `yarn` after creating the rule to get all the dependencies
* Investigate why `spinner.fail` doesn't exist

**Comment by sarvaje** [comment] 2018-05-10 18:32
I am not able to reproduce the `spinner` error :(

**Comment by sarvaje** [comment] 2018-06-04 22:10
The spinner dependency will be removed once https://github.com/sonarwhal/sonarwhal/pull/1113 is merged. So we should be able to close this issue after the merge.

**Closed** 2018-06-06 21:39 UTC
